### ISSUE TITLE
space[@type="descender"] for tfaPallava091

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfa-pallava-epigraphy#1]
Dear @manufrancis, 

As discussed, the value `descender` for `space[@type]` is no longer available. It is use once in your repository for [tfaPallava091](https://github.com/erc-dharma/tfa-pallava-epigraphy/blob/master/texts/xml/tfaPallava091.xml), can I let you change it and move the information into the apparatus? 

Thanks

**Comment by manufrancis** [comment]
Done!
Thanks for spotting it.
