### ISSUE TITLE
Updating the numbering of lines

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfa-pallava-epigraphy#2]
Dear @manufrancis, 

Daniel has updated the numbering schema, see EG, p.21. Now, it is required that line numbers are unique. Since your files use textpart, you shouldn't have to change it but could you take a look at the following files to make sure it is still conformant please? 
-tfaPallava052
-tfaPallava361
-tfaPallava362

**Comment by manufrancis** [comment]
Dear @ajaniak,
Will do. 
In fact I am considering now to split these files into several files (3 editions becoming 12 editions).
Will wait for Adeline's advise.

**Comment by ajaniak** [comment]
I wonder if it could be helpful for you to still have all this 12 editions in only 3 files. It could be handled with one of the following structure:

```
<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">
 <teiHeader/>
 <TEI>
  <teiHeader/>
  <text/>
 </TEI>
 <TEI>
  <teiHeader/>
  <text/>
 </TEI>
</teiCorpus>
```
or 
```
<TEI xmlns="http://www.tei-c.org/ns/1.0">
 <teiHeader/>
 <TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader/>
  <text/>
 </TEI>
 <TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader/>
  <text/>
 </TEI>
</TEI>
```

**Comment by arlogriffiths** [comment]
Axelle: There was discussion about TEI corpus on the MARKUP list a few months ago. Have you read what was the outcome of that discussion? (I don’t remember myself what it was.)

A

Le 25 mars 2020 à 09:09, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



I wonder if it could be helpful for you to still have all this 12 editions in only 3 files. It could be handled with one of the following structure:

<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">
 <teiHeader/>
 <TEI>
  <teiHeader/>
  <text/>
 </TEI>
 <TEI>
  <teiHeader/>
  <text/>
 </TEI>
</teiCorpus>


or

<TEI xmlns="http://www.tei-c.org/ns/1.0">
 <teiHeader/>
 <TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader/>
  <text/>
 </TEI>
 <TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader/>
  <text/>
 </TEI>
</TEI>

**Comment by ajaniak** [comment]
The Markup decided in favor of adding the `<teiCorpus>` in the validating Schema released in october 2019. A part of the discussion was will the element be deprecated by the TEI-C, it seems that at some point, it has been plan to allow the nesting of `<TEI>`rather than using `<teiCorpus>`.
Another part of the exchange was about the relevance. It isn't if the purpose is just to link several XMl files together, but it can make sense when metadata for the group is needed as well as metadata for each inscription.
