### ISSUE TITLE
DHARMA_INSPallava00218 : unclear

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfa-pallava-epigraphy#3]
@manufrancis, 

in the file DHARMA_InsPallava00218.xml, 2nd entry in the apparatus for the line 10: 
```
<app loc="10">
         <lem>Eṉ ‡ <unclear>ṟa</unclear>lai</lem>
         <rdg source="bib:SubrahmanyaAiyer1928_01">Eṉ ṟa<unclear/>lai</rdg>
</app>
```
Do you want to display this empty `<unclear/>`? if yes, how? The current display would be `()`:
```
10 Eṉ ‡ (ṟa)lai ◇ Eṉ ṟa()lai KVSA
```

I will let you think if such a feature should be considered with the others PIs and so moved to the project-documentation. 
Thanks

**Comment by manufrancis** [comment]
Merci, Axelle !
Erreur d'encodage de ma part ;-)
