### ISSUE TITLE
DHARMA_INSPallava00036.xml

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/tfa-pallava-epigraphy#6]
Brackets for unclear not display inside `<choice><orig>` but the content is display.

**Comment by ajaniak** [comment]
@manufrancis, pour `<unclear>` dans `choice/orig`, les parenthèses tu les veux en rose ou en notBold et en noir comme ailleurs? 
<img width="362" alt="Capture d’écran 2020-10-14 à 11 49 07" src="https://user-images.githubusercontent.com/33328906/95972926-50efea80-0e13-11eb-87e7-b8388a7f0820.png">

**Comment by ajaniak** [comment]
By the way, it would give this : 
<img width="348" alt="Capture d’écran 2020-10-14 à 12 02 41" src="https://user-images.githubusercontent.com/33328906/95974394-36b70c00-0e15-11eb-9a35-936aca140dd1.png">

**Comment by manufrancis** [comment]
Dear Axelle,
I opt for not bold and coloured, like this:
![image](https://user-images.githubusercontent.com/905870/96991289-850c8f00-1528-11eb-9973-50fa74d808fd.png)

**Comment by ajaniak** [comment]
The code is already set for it. Thanks for your answer
